class ColorValues {
  static Map<String, String>? getXmlString = {
    "com.android.contacts": '''
      <?xml version="1.0" encoding="utf-8"?>
      <MIUI_Theme_Values template="LightTemplate">
        <color name="dialer_accent_color" >#ffff8cee</color>
        <color name="dialer_accent_color_pressed" >#ffff8cee</color>
        <color name="tab_text_color_focused" >#ffff8cee</color>
        <color name="contacts_accent_color" >#ffff8cee</color>
        <color name="accent_color_light" package="miui">#ffff8cee</color>
        <color name="picker_action_bar_tab_text_color_selected" >#ffff8cee</color>
        <color name="search_action_mode_cancel_text_color_normal" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_search_action_mode_cancel_text_color_normal" >#ffff8cee</color>
        <color name="miuix_appcompat_search_action_mode_cancel_text_color_pressed" >#ffff8cee</color>
        <color name="cloud_recommend_msg_color" >#ffff8cee</color>
        <color name="list_text_color_checked_light" package="miui">#ffff8cee</color>
        <color name="list_secondary_text_color_checked_light" package="miui">#ffff8cee</color>
        <color name="miuix_preference_secondary_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_preference_list_secondary_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_preference_btn_radio_arrow_color" >#ffff8cee</color>
        <color name="action_button_positive_color" >#ffff8cee</color>
        <color name="number_picker_highlight_text_color" package="miui">#ffff8cee</color>
        <color name="number_picker_label_color" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_alphabet_indexer_highlight_text_color" >#ffff8cee</color>
        <color name="editor_scan_businesscard_btn_txt_color" >#ffff8cee</color>
        <color name="high_light_text" >#ffff8cee</color>
        <color name="highlight_normal_light" package="miui">#ffff8cee</color>
        <color name="highlight_pressed_light" package="miui">#ffff8cee</color>
        <color name="numberpicker_label" package="miui">#ffff8cee</color>
        <color name="numberpicker_highlight_text" package="miui">#ffff8cee</color>
        <color name="contact_detail_action_item_textcolor" >#ffff8cee</color>
        <color name="dropdown_popup_list_text_color_checked_light" package="miui">#ffff8cee</color>
        <color name="miuix_compat_list_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_compat_list_secondary_text_color_checked_light" >#ffff8cee</color>
        <color name="text_edit_action_popup_text_pressed" package="miui">#ffff8cee</color>
        <color name="text_edit_action_popup_more_normal_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_highlight_normal_light" >#ffff8cee</color>
        <color name="miuix_appcompat_highlight_pressed_light" >#ffff8cee</color>
        <color name="miuix_appcompat_number_picker_hint_color" >#ffff8cee</color>
        <color name="miuix_appcompat_number_picker_highlight_color" >#ffff8cee</color>
        <color name="miuix_appcompat_number_picker_label_color" >#ffff8cee</color>
        <color name="button_bg_color_normal_light" >#ffff8cee</color>
        <color name="miuix_appcompat_dropdown_popup_list_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_appcompat_list_secondary_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_appcompat_list_text_color_checked_light" >#ffff8cee</color>
        <color name="visual_check_borderlayout_bg_stroke_color" >#ffff8cee</color>
        <color name="visual_check_textview_checked_text_color" >#ffff8cee</color>
        <color name="bh_color_main_text_blue" >#ffff8cee</color>
        <color name="device_text_checked_color" >#ffff8cee</color>
        <color name="button_bg_primary_color_normal_light" package="miui">#ffff8cee</color>
        <color name="button_bg_primary_color_pressed_light" package="miui">#ffff8cee</color>
        <color name="button_bg_color_warn_normal_light" package="miui">#ffff8cee</color>
        <color name="button_bg_color_warn_pressed_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_button_bg_primary_color_normal_light" >#ffff8cee</color>
        <color name="miuix_appcompat_button_bg_primary_color_pressed_light" >#ffff8cee</color>
        <color name="miuix_appcompat_button_bg_color_warn_normal_light" >#ffff8cee</color>
        <color name="sliding_button_bar_on_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_sliding_button_bar_on_light" >#ffff8cee</color>
        <color name="svg_icon_color_blue_normal_light" package="miui">#ffff8cee</color>
        <color name="svg_icon_color_blue_selected_light" package="miui">#ffff8cee</color>
        <color name="action_mode_button_text_color_selected_light" package="miui">#ffff8cee</color>
        <color name="action_button_text_color_selected_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_svg_icon_color_blue_normal_light" >#ffff8cee</color>
        <color name="miuix_appcompat_svg_icon_color_blue_selected_light" >#ffff8cee</color>
        <color name="miuix_appcompat_action_mode_button_text_color_selected_light" >#ffff8cee</color>
        <color name="miuix_appcompat_action_button_text_color_selected_light" >#ffff8cee</color>
        <color name="checkbox_btn_on_background_color_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_checkbox_btn_on_background_color_light" >#ffff8cee</color>
        <color name="miuix_appcompat_edit_text_border_color" >#ffff8cee</color>
        <color name="decor_view_status_guard" >#ffff8cee</color>
        <color name="bh_color_bg_waterbox" >#ffff8cee</color>
        <color name="bh_orange" >#ffff8cee</color>
        <color name="t9_list_item_text_highlight" >#ffff8cee</color>
        <color name="dialer_digits_text_color" >#ffff8cee</color>
      </MIUI_Theme_Values>
    ''',
    "com.android.mms": '''
          <?xml version="1.0" encoding="utf-8"?>
            <MIUI_Theme_Values template="LightTemplate">
              <color name="action_bar_tab_text_color_selected_light" package="miui">#ffff8cee</color>
              <color name="highlight_normal_light" package="miui">#ffff8cee</color>
              <color name="text_color_mi_recipient" >#ffff8cee</color>
              <color name="miuix_appcompat_action_bar_tab_text_color_selected_light" >#ffff8cee</color>
              <color name="miuix_appcompat_highlight_normal_light" >#ffff8cee</color>
              <color name="search_action_mode_cancel_text_color_normal" package="miui">#ffff8cee</color>
              <color name="search_action_mode_cancel_text_color_pressed" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_search_action_mode_cancel_text_color_normal" >#ffff8cee</color>
              <color name="miuix_appcompat_search_action_mode_cancel_text_color_pressed" >#ffff8cee</color>
              <color name="highlight_pressed_light" package="miui">#ffff8cee</color>
              <color name="highlight_text_color" >#ffff8cee</color>
              <color name="recommend_bar_button_ok_text_color" >#ffff8cee</color>
              <color name="miuix_sbl_locked_blue" >#ffff8cee</color>
              <color name="miuix_sbl_locked_text_blue" >#ffff8cee</color>
              <color name="unread_icon" >#ffff8cee</color>
              <color name="sim_indicator_color_selected" >#ffff8cee</color>
              <color name="audio_progress_title_disabled" >#ffff8cee</color>
              <color name="audio_bottom_color" >#ffff8cee</color>
              <color name="security_alert_color" >#ffff8cee</color>
              <color name="number_picker_highlight_text_color" package="miui">#ffff8cee</color>
              <color name="number_picker_label_color" package="miui">#ffff8cee</color>
              <color name="button_bg_dialog_color_pressed_light" package="miui">#ffff8cee</color>
              <color name="dropdown_popup_list_text_color_checked_light" package="miui">#ffff8cee</color>
              <color name="text_edit_action_popup_text_pressed" package="miui">#ffff8cee</color>
              <color name="text_edit_action_popup_more_normal_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_highlight_pressed_light" >#ffff8cee</color>
              <color name="miuix_appcompat_list_text_color_checked_light" >#ffff8cee</color>
              <color name="miuix_appcompat_number_picker_highlight_text_color" >#ffff8cee</color>
              <color name="miuix_appcompat_dropdown_popup_list_text_color_checked_light" >#ffff8cee</color>
              <color name="miuix_appcompat_text_edit_action_popup_text_pressed" >#ffff8cee</color>
              <color name="miuix_appcompat_text_edit_action_popup_more_normal_light" >#ffff8cee</color>
              <color name="miuix_appcompat_number_picker_highlight_color" >#ffff8cee</color>
              <color name="miuix_appcompat_number_picker_label_color" >#ffff8cee</color>
              <color name="miuix_compat_list_text_color_checked_light" >#ffff8cee</color>
              <color name="button_bg_primary_color_normal_light" package="miui">#ffff8cee</color>
              <color name="button_bg_primary_color_pressed_light" package="miui">#ffff8cee</color>
              <color name="button_bg_color_warn_normal_light" package="miui">#ffff8cee</color>
              <color name="button_bg_color_warn_pressed_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_button_bg_color_warn_normal_light" >#ffff8cee</color>
              <color name="miuix_appcompat_button_bg_color_warn_pressed_light" >#ffff8cee</color>
              <color name="miuix_appcompat_button_bg_primary_color_normal_light" >#ffff8cee</color>
              <color name="miuix_appcompat_button_bg_primary_color_pressed_light" >#ffff8cee</color>
              <color name="edit_text_border_color" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_edit_text_border_color" >#ffff8cee</color>
              <color name="fab_bg_color" >#ffff8cee</color>
              <color name="understand_button_text" >#ffff8cee</color>
              <color name="text_color_message_in_highlight" >#ffff8cee</color>
              <color name="text_color_message_in_highlight_pressed" >#ffff8cee</color>
              <color name="text_color_attachment_edit_phrase" >#ffff8cee</color>
              <color name="ic_insert_contact_color" >#ffff8cee</color>
              <color name="text_color_bottom_menu_button" >#ffff8cee</color>
              <color name="train_card_action_text_primary" >#ffff8cee</color>
              <color name="link_text_color_normal" >#ffff8cee</color>
              <color name="link_text_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_link_text_light" >#ffff8cee</color>
              <color name="understand_float_text_color" >#ffff8cee</color>
              <color name="sliding_button_bar_on_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_sliding_button_bar_on_light" >#ffff8cee</color>
              <color name="svg_icon_color_blue_normal_light" package="miui">#ffff8cee</color>
              <color name="svg_icon_color_blue_selected_light" package="miui">#ffff8cee</color>
              <color name="action_button_text_color_selected_light" package="miui">#ffff8cee</color>
              <color name="action_mode_button_text_color_selected_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_svg_icon_color_blue_normal_light" >#ffff8cee</color>
              <color name="miuix_appcompat_svg_icon_color_blue_selected_light" >#ffff8cee</color>
              <color name="miuix_appcompat_action_button_text_color_selected_light" >#ffff8cee</color>
              <color name="miuix_appcompat_action_mode_button_text_color_selected_light" >#ffff8cee</color>
              <color name="checkbox_btn_on_background_color_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_checkbox_btn_on_background_color_light" >#ffff8cee</color>
            </MIUI_Theme_Values>
      ''',
    "com.android.systemui": '''
          <?xml version="1.0" encoding="utf-8"?>
            <MIUI_Theme_Values template="LightTemplate">
              <color name="notification_actions_button_color" >#ffff8cee</color>
              <color name="notification_overflow_number_color" >#ffff8cee</color>
              <color name="notification_action_text_color" >#ffff8cee</color>
              <color name="notification_default_color_light" package="android">#ffff8cee</color>
              <color name="notification_setting_button_color" >#ffff8cee</color>
              <color name="notification_group_collapsed_button_color" >#ffff8cee</color>
              <color name="recent_tick_anim_color" >#ffff8cee</color>
              <color name="qs_control_tile_icon_enable_color" >#ffff8cee</color>
              <color name="qs_control_big_tile_green_bg" >#ffff8cee</color>
              <color name="qs_control_big_tile_blue_bg" >#ffff8cee</color>
              <color name="cc_qs_tile_icon_bg_color_active" >#ffff8cee</color>
              <color name="qs_detail_item_selected_color" >#ffff8cee</color>
              <color name="qs_tile_icon_bg_enabled_color" >#ffff8cee</color>
              <color name="sliding_button_bar_on_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_sliding_button_bar_on_light" >#ffff8cee</color>
              <color name="status_bar_network_flow_exceed_color" >#ffff8cee</color>
              <color name="cc_qs_tile_icon_bg_color_active_battery_related" >#ffff8cee</color>
              <color name="qs_control_brightness_progress_color" >#ffff8cee</color>
              <color name="qs_control_tiles_expand_indicator_color" >#ffff8cee</color>
              <color name="qs_control_big_tile_white_bg" >#ffff8cee</color>
              <color name="qs_tile_icon_bg_disabled_color" >#ffffffff</color>
            </MIUI_Theme_Values>'''
  };
}
