class ColorValues {
  static Map<String, String>? getXmlString = {
    "com.android.contacts": '''
      <?xml version="1.0" encoding="utf-8"?>
      <MIUI_Theme_Values template="LightTemplate">
        <color name="dialer_accent_color" >#ffff8cee</color>
        <color name="dialer_accent_color_pressed" >#ffff8cee</color>
        <color name="tab_text_color_focused" >#ffff8cee</color>
        <color name="contacts_accent_color" >#ffff8cee</color>
        <color name="accent_color_light" package="miui">#ffff8cee</color>
        <color name="picker_action_bar_tab_text_color_selected" >#ffff8cee</color>
        <color name="search_action_mode_cancel_text_color_normal" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_search_action_mode_cancel_text_color_normal" >#ffff8cee</color>
        <color name="miuix_appcompat_search_action_mode_cancel_text_color_pressed" >#ffff8cee</color>
        <color name="cloud_recommend_msg_color" >#ffff8cee</color>
        <color name="list_text_color_checked_light" package="miui">#ffff8cee</color>
        <color name="list_secondary_text_color_checked_light" package="miui">#ffff8cee</color>
        <color name="miuix_preference_secondary_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_preference_list_secondary_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_preference_btn_radio_arrow_color" >#ffff8cee</color>
        <color name="action_button_positive_color" >#ffff8cee</color>
        <color name="number_picker_highlight_text_color" package="miui">#ffff8cee</color>
        <color name="number_picker_label_color" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_alphabet_indexer_highlight_text_color" >#ffff8cee</color>
        <color name="editor_scan_businesscard_btn_txt_color" >#ffff8cee</color>
        <color name="high_light_text" >#ffff8cee</color>
        <color name="highlight_normal_light" package="miui">#ffff8cee</color>
        <color name="highlight_pressed_light" package="miui">#ffff8cee</color>
        <color name="numberpicker_label" package="miui">#ffff8cee</color>
        <color name="numberpicker_highlight_text" package="miui">#ffff8cee</color>
        <color name="contact_detail_action_item_textcolor" >#ffff8cee</color>
        <color name="dropdown_popup_list_text_color_checked_light" package="miui">#ffff8cee</color>
        <color name="miuix_compat_list_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_compat_list_secondary_text_color_checked_light" >#ffff8cee</color>
        <color name="text_edit_action_popup_text_pressed" package="miui">#ffff8cee</color>
        <color name="text_edit_action_popup_more_normal_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_highlight_normal_light" >#ffff8cee</color>
        <color name="miuix_appcompat_highlight_pressed_light" >#ffff8cee</color>
        <color name="miuix_appcompat_number_picker_hint_color" >#ffff8cee</color>
        <color name="miuix_appcompat_number_picker_highlight_color" >#ffff8cee</color>
        <color name="miuix_appcompat_number_picker_label_color" >#ffff8cee</color>
        <color name="button_bg_color_normal_light" >#ffff8cee</color>
        <color name="miuix_appcompat_dropdown_popup_list_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_appcompat_list_secondary_text_color_checked_light" >#ffff8cee</color>
        <color name="miuix_appcompat_list_text_color_checked_light" >#ffff8cee</color>
        <color name="visual_check_borderlayout_bg_stroke_color" >#ffff8cee</color>
        <color name="visual_check_textview_checked_text_color" >#ffff8cee</color>
        <color name="bh_color_main_text_blue" >#ffff8cee</color>
        <color name="device_text_checked_color" >#ffff8cee</color>
        <color name="button_bg_primary_color_normal_light" package="miui">#ffff8cee</color>
        <color name="button_bg_primary_color_pressed_light" package="miui">#ffff8cee</color>
        <color name="button_bg_color_warn_normal_light" package="miui">#ffff8cee</color>
        <color name="button_bg_color_warn_pressed_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_button_bg_primary_color_normal_light" >#ffff8cee</color>
        <color name="miuix_appcompat_button_bg_primary_color_pressed_light" >#ffff8cee</color>
        <color name="miuix_appcompat_button_bg_color_warn_normal_light" >#ffff8cee</color>
        <color name="sliding_button_bar_on_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_sliding_button_bar_on_light" >#ffff8cee</color>
        <color name="svg_icon_color_blue_normal_light" package="miui">#ffff8cee</color>
        <color name="svg_icon_color_blue_selected_light" package="miui">#ffff8cee</color>
        <color name="action_mode_button_text_color_selected_light" package="miui">#ffff8cee</color>
        <color name="action_button_text_color_selected_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_svg_icon_color_blue_normal_light" >#ffff8cee</color>
        <color name="miuix_appcompat_svg_icon_color_blue_selected_light" >#ffff8cee</color>
        <color name="miuix_appcompat_action_mode_button_text_color_selected_light" >#ffff8cee</color>
        <color name="miuix_appcompat_action_button_text_color_selected_light" >#ffff8cee</color>
        <color name="checkbox_btn_on_background_color_light" package="miui">#ffff8cee</color>
        <color name="miuix_appcompat_checkbox_btn_on_background_color_light" >#ffff8cee</color>
        <color name="miuix_appcompat_edit_text_border_color" >#ffff8cee</color>
        <color name="decor_view_status_guard" >#ffff8cee</color>
        <color name="bh_color_bg_waterbox" >#ffff8cee</color>
        <color name="bh_orange" >#ffff8cee</color>
        <color name="t9_list_item_text_highlight" >#ffff8cee</color>
        <color name="dialer_digits_text_color" >#ffff8cee</color>
      </MIUI_Theme_Values>
    ''',
    "com.android.mms": '''
          <?xml version="1.0" encoding="utf-8"?>
            <MIUI_Theme_Values template="LightTemplate">
              <color name="action_bar_title_text_color_light" package="miui">#cc000000</color>
              <color name="action_mode_title_text_color_light" package="miui">#cc000000</color>
              <color name="flat_list_title_color" >#cc000000</color>
              <color name="action_title_color_light" package="miui">#cc000000</color>
              <color name="action_bar_tab_text_color_pressed_light" package="miui">#cc000000</color>
              <color name="new_message_popup_sender_color" >#cc000000</color>
              <color name="miuix_appcompat_action_bar_title_text_color_light" >#cc000000</color>
              <color name="miuix_appcompat_action_mode_title_text_color_light" >#cc000000</color>
              <color name="miuix_appcompat_action_title_color_light" >#cc000000</color>
              <color name="miuix_appcompat_action_bar_tab_text_color_pressed_light" >#cc000000</color>
              <color name="action_bar_subtitle_text_light" package="miui">#99000000</color>
              <color name="action_bar_tab_text_color_normal_light" package="miui">#99000000</color>
              <color name="miuix_appcompat_action_bar_subtitle_text_light" >#99000000</color>
              <color name="miuix_appcompat_action_bar_tab_text_color_normal_light" >#99000000</color>
              <color name="tab_normal_text_color" >#66000000</color>
              <color name="tab_active_text_color" >#cc000000</color>
              <color name="action_bar_tab_text_color_selected_light" package="miui">#ffff8cee</color>
              <color name="highlight_normal_light" package="miui">#ffff8cee</color>
              <color name="text_color_mi_recipient" >#ffff8cee</color>
              <color name="miuix_appcompat_action_bar_tab_text_color_selected_light" >#ffff8cee</color>
              <color name="miuix_appcompat_highlight_normal_light" >#ffff8cee</color>
              <color name="edit_text_search_bg_color_light" package="miui">#0d000000</color>
              <color name="miuix_appcompat_edit_text_search_bg_color_light" >#0d000000</color>
              <color name="edit_text_search_hint_color_light" package="miui">#66000000</color>
              <color name="miuix_appcompat_edit_text_search_hint_color_light" >#66000000</color>
              <color name="edit_text_search_color_light" package="miui">#e6000000</color>
              <color name="miuix_appcompat_edit_text_search_color_light" >#e6000000</color>
              <color name="search_action_mode_cancel_text_color_normal" package="miui">#ffff8cee</color>
              <color name="search_action_mode_cancel_text_color_pressed" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_search_action_mode_cancel_text_color_normal" >#ffff8cee</color>
              <color name="miuix_appcompat_search_action_mode_cancel_text_color_pressed" >#ffff8cee</color>
              <color name="miuix_appcompat_cloud_state_message_bg_color_normal_light" >#0d000000</color>
              <color name="recommend_bar_home_background_color" >#0d000000</color>
              <color name="miuix_appcompat_cloud_status_highlight_text_color_light" >#fff22424</color>
              <color name="recommend_bar_title_color" >#e6000000</color>
              <color name="miuix_sbl_locked_gray" >#e6000000</color>
              <color name="miuix_sbl_locked_text_gray" >#e6000000</color>
              <color name="list_text_color_normal_light" package="miui">#e6000000</color>
              <color name="list_text_color_pressed_light" package="miui">#e6000000</color>
              <color name="list_text_color_checked_light" package="miui">#e6000000</color>
              <color name="miuix_preference_primary_text_color_light" >#e6000000</color>
              <color name="preference_primary_text_color_light" package="miui">#e6000000</color>
              <color name="preference_primary_text_color_pressed_light" package="miui">#e6000000</color>
              <color name="recipient_text_color" >#e6000000</color>
              <color name="text_color_recipient_item" >#e6000000</color>
              <color name="sim_indicator_color_normal" >#e6000000</color>
              <color name="text_color_black" >#e6000000</color>
              <color name="audio_progress_title_normal" >#e6000000</color>
              <color name="audio_bottom_default_color" >#e6000000</color>
              <color name="bright_foreground_light" package="miui">#e6000000</color>
              <color name="flatshow_pageno_text_color" >#e6000000</color>
              <color name="contact_card_title_text_color" >#e6000000</color>
              <color name="contact_card_item_title_text_color" >#e6000000</color>
              <color name="verfication_card_text_primary" >#e6000000</color>
              <color name="normal_card_text_primary" >#e6000000</color>
              <color name="verfication_card_action_text_primary" >#e6000000</color>
              <color name="card_original_text_color" >#e6000000</color>
              <color name="card_original_text_primary" >#e6000000</color>
              <color name="edit_text_dialog_color_normal_light" package="miui">#e6000000</color>
              <color name="dialog_primary_text" >#e6000000</color>
              <color name="dialog_title_text_color" package="miui">#e6000000</color>
              <color name="dialog_message_text_color_light" package="miui">#e6000000</color>
              <color name="dialog_list_text_color_normal_light" package="miui">#e6000000</color>
              <color name="dialog_list_text_color_pressed_light" package="miui">#e6000000</color>
              <color name="dialog_list_text_color_checked_light" package="miui">#e6000000</color>
              <color name="menu_list_text_color_normal_light" package="miui">#e6000000</color>
              <color name="menu_list_text_color_pressed_light" package="miui">#e6000000</color>
              <color name="immersion_text_color_normal_light" package="miui">#e6000000</color>
              <color name="immersion_text_color_pressed_light" package="miui">#e6000000</color>
              <color name="dropdown_popup_list_text_color_normal_light" package="miui">#e6000000</color>
              <color name="dropdown_popup_list_text_color_pressed_light" package="miui">#e6000000</color>
              <color name="text_edit_action_popup_text_normal" package="miui">#e6000000</color>
              <color name="progressbar_indeterminate_circle_color_light" package="miui">#e6000000</color>
              <color name="text_edit_action_popup_title_normal_light" package="miui">#e6000000</color>
              <color name="miuix_appcompat_list_text_color_normal_light" >#e6000000</color>
              <color name="miuix_appcompat_list_text_color_pressed_light" >#e6000000</color>
              <color name="miuix_appcompat_preference_primary_text_color_light" >#e6000000</color>
              <color name="miuix_appcompat_preference_primary_text_color_pressed_light" >#e6000000</color>
              <color name="miuix_appcompat_bright_foreground_light" >#e6000000</color>
              <color name="miuix_appcompat_dialog_list_text_color_normal_light" >#e6000000</color>
              <color name="miuix_appcompat_dialog_list_text_color_checked_light" >#e6000000</color>
              <color name="miuix_appcompat_menu_list_text_color_normal_light" >#e6000000</color>
              <color name="miuix_appcompat_immersion_text_color_normal_light" >#e6000000</color>
              <color name="miuix_appcompat_dropdown_popup_list_text_color_normal_light" >#e6000000</color>
              <color name="miuix_appcompat_text_edit_action_popup_text_normal" >#e6000000</color>
              <color name="miuix_appcompat_progressbar_indeterminate_circle_color_light" >#e6000000</color>
              <color name="miuix_appcompat_text_edit_action_popup_title_normal_light" >#e6000000</color>
              <color name="miuix_appcompat_text_color_primary_light" >#e6000000</color>
              <color name="miuix_appcompat_dialog_title_text_color" >#e6000000</color>
              <color name="miuix_appcompat_edit_text_dialog_color_normal_light" >#e6000000</color>
              <color name="miuix_appcompat_cloud_count_normal_text_color_light" >#99000000</color>
              <color name="recommend_bar_button_close_text_color" >#99000000</color>
              <color name="list_secondary_text_color_normal_light" package="miui">#99000000</color>
              <color name="list_secondary_text_color_pressed_light" package="miui">#99000000</color>
              <color name="list_secondary_text_color_checked_light" package="miui">#99000000</color>
              <color name="miuix_preference_list_secondary_text_color_normal_light" >#99000000</color>
              <color name="miuix_preference_list_secondary_text_color_pressed_light" >#99000000</color>
              <color name="miuix_preference_list_secondary_text_color_checked_light" >#99000000</color>
              <color name="sim_number_color_normal" >#99000000</color>
              <color name="sim_card_number_color" >#99000000</color>
              <color name="list_secondary_text_color_normal_light" >#99000000</color>
              <color name="list_secondary_text_color_pressed_light" >#99000000</color>
              <color name="text_color_message_alert_secondary" >#99000000</color>
              <color name="text_color_message_alert_secondary_pressed" >#99000000</color>
              <color name="security_alert_hint_text_color" >#99000000</color>
              <color name="contact_card_item_tag_text_color" >#99000000</color>
              <color name="tab_list_header_title" >#99000000</color>
              <color name="normal_card_text_secondary" >#99000000</color>
              <color name="verficationl_card_text_secondary" >#99000000</color>
              <color name="sms_card_body_secondary" >#99000000</color>
              <color name="card_body_text_color" >#99000000</color>
              <color name="dialog_secondary_text" >#99000000</color>
              <color name="dialog_tertiary_text" >#99000000</color>
              <color name="number_picker_hint_text_color" package="miui">#99000000</color>
              <color name="dialog_checkbox_text_color_light" package="miui">#99000000</color>
              <color name="button_text_color_light" package="miui">#99000000</color>
              <color name="button_text_color_dialog_light" package="miui">#99000000</color>
              <color name="text_edit_action_popup_summary_normal_light" package="miui">#99000000</color>
              <color name="miuix_appcompat_list_secondary_text_color_normal_light" >#99000000</color>
              <color name="miuix_appcompat_list_secondary_text_color_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_list_secondary_text_color_checked_light" >#99000000</color>
              <color name="miuix_appcompat_number_picker_hint_text_color" >#99000000</color>
              <color name="miuix_appcompat_dialog_checkbox_text_color_light" >#99000000</color>
              <color name="miuix_appcompat_dialog_list_text_color_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_menu_list_text_color_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_immersion_text_color_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_dropdown_popup_list_text_color_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_text_edit_action_popup_summary_normal_light" >#99000000</color>
              <color name="miuix_appcompat_dialog_message_text_color_light" >#99000000</color>
              <color name="miuix_appcompat_button_text_color_light" >#99000000</color>
              <color name="miuix_appcompat_spinner_text_color_light" >#99000000</color>
              <color name="miuix_appcompat_number_picker_hint_color" >#99000000</color>
              <color name="miuix_preference_right_text_color_normal_light" >#99000000</color>
              <color name="miuix_preference_right_text_color_disable_light" >#99000000</color>
              <color name="miuix_compat_integrated_spinner_text_color_light" >#99000000</color>
              <color name="miuix_compat_list_text_color_disable_light" >#99000000</color>
              <color name="miuix_compat_list_text_color_normal_light" >#99000000</color>
              <color name="miuix_compat_list_text_color_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_cloud_arrow_color_light" >#99000000</color>
              <color name="list_text_color_disable_light" package="miui">#4d000000</color>
              <color name="list_secondary_text_color_disable_light" package="miui">#4d000000</color>
              <color name="miuix_preference_primary_text_color_disable_light" >#4d000000</color>
              <color name="preference_primary_text_color_disable_light" package="miui">#4d000000</color>
              <color name="miuix_preference_secondary_text_color_disable_light" >#4d000000</color>
              <color name="miuix_preference_arrow_right_disable_fill_color_light" >#4d000000</color>
              <color name="miuix_preference_list_secondary_text_color_disable_light" >#4d000000</color>
              <color name="recent_recipient_checked_text_color" >#4d000000</color>
              <color name="list_secondary_text_color_disable_light" >#4d000000</color>
              <color name="bright_foreground_light_disabled" package="miui">#4d000000</color>
              <color name="tab_list_header_date" >#4d000000</color>
              <color name="edit_text_dialog_color_disabled_light" package="miui">#4d000000</color>
              <color name="disabled_text_light" package="miui">#4d000000</color>
              <color name="button_text_color_dialog_disabled_light" package="miui">#4d000000</color>
              <color name="dialog_list_text_color_disabled_light" package="miui">#4d000000</color>
              <color name="menu_list_text_color_disabled_light" package="miui">#4d000000</color>
              <color name="immersion_text_color_disable_light" package="miui">#4d000000</color>
              <color name="dropdown_popup_list_text_color_disabled_light" package="miui">#4d000000</color>
              <color name="miuix_appcompat_list_text_color_disable_light" >#4d000000</color>
              <color name="miuix_appcompat_list_secondary_text_color_disable_light" >#4d000000</color>
              <color name="miuix_appcompat_preference_primary_text_color_disable_light" >#4d000000</color>
              <color name="miuix_appcompat_bright_foreground_light_disabled" >#4d000000</color>
              <color name="miuix_appcompat_edit_text_dialog_color_disabled_light" >#4d000000</color>
              <color name="miuix_appcompat_disabled_text_light" >#4d000000</color>
              <color name="miuix_appcompat_dialog_list_text_color_disabled_light" >#4d000000</color>
              <color name="miuix_appcompat_menu_list_text_color_disabled_light" >#4d000000</color>
              <color name="miuix_appcompat_immersion_text_color_disable_light" >#4d000000</color>
              <color name="miuix_appcompat_dropdown_popup_list_text_color_disabled_light" >#4d000000</color>
              <color name="miuix_appcompat_integrated_spinner_text_color_disable_light" >#4d000000</color>
              <color name="miuix_appcompat_arrow_right_disable_fill_color_light" >#4d000000</color>
              <color name="blank_page_text_color_light" package="miui">#66000000</color>
              <color name="miuix_appcompat_cloud_status_normal_text_color_light" >#66000000</color>
              <color name="recommend_bar_message_color" >#66000000</color>
              <color name="conversation_date_color" >#66000000</color>
              <color name="miuix_preference_secondary_text_color_light" >#66000000</color>
              <color name="miuix_preference_secondary_text_color_checked_light" >#66000000</color>
              <color name="miuix_preference_arrow_right_normal_fill_color_light" >#66000000</color>
              <color name="miuix_preference_arrow_right_pressed_fill_color_light" >#66000000</color>
              <color name="list_view_item_group_header_text_light" package="miui">#66000000</color>
              <color name="new_message_label_color" >#66000000</color>
              <color name="recent_label_text_color" >#66000000</color>
              <color name="hint_foreground_light" package="miui">#66000000</color>
              <color name="ic_contact_card_arrow_right_color" >#66000000</color>
              <color name="hint_edit_text_dialog_color_light" package="miui">#66000000</color>
              <color name="text_edit_action_popup_info_normal_light" package="miui">#66000000</color>
              <color name="miuix_appcompat_blank_page_text_color_light" >#66000000</color>
              <color name="miuix_appcompat_list_view_item_group_header_text_light" >#66000000</color>
              <color name="miuix_appcompat_hint_foreground_light" >#66000000</color>
              <color name="miuix_appcompat_text_edit_action_popup_info_normal_light" >#66000000</color>
              <color name="miuix_preference_right_text_color_light" >#66000000</color>
              <color name="miuix_appcompat_integrated_spinner_text_color_light" >#66000000</color>
              <color name="miuix_appcompat_hint_edit_text_dialog_color_light" >#66000000</color>
              <color name="miuix_appcompat_integrated_spinner_text_color_normal_light" >#66000000</color>
              <color name="miuix_appcompat_arrow_right_normal_fill_color_light" >#66000000</color>
              <color name="miuix_appcompat_arrow_right_pressed_fill_color_light" >#66000000</color>
              <color name="miuix_preference_category_text_color_light" >#ff8c93b0</color>
              <color name="visual_guidance_layout_bg_color" >#00ffffff</color>
              <color name="highlight_disabled_light" package="miui">#7f4eaa8a</color>
              <color name="miuix_appcompat_highlight_disabled_light" >#7f4eaa8a</color>
              <color name="highlight_pressed_light" package="miui">#ffff8cee</color>
              <color name="highlight_text_color" >#ffff8cee</color>
              <color name="recommend_bar_button_ok_text_color" >#ffff8cee</color>
              <color name="miuix_sbl_locked_blue" >#ffff8cee</color>
              <color name="miuix_sbl_locked_text_blue" >#ffff8cee</color>
              <color name="unread_icon" >#ffff8cee</color>
              <color name="sim_indicator_color_selected" >#ffff8cee</color>
              <color name="audio_progress_title_disabled" >#ffff8cee</color>
              <color name="audio_bottom_color" >#ffff8cee</color>
              <color name="security_alert_color" >#ffff8cee</color>
              <color name="number_picker_highlight_text_color" package="miui">#ffff8cee</color>
              <color name="number_picker_label_color" package="miui">#ffff8cee</color>
              <color name="button_bg_dialog_color_pressed_light" package="miui">#ffff8cee</color>
              <color name="dropdown_popup_list_text_color_checked_light" package="miui">#ffff8cee</color>
              <color name="text_edit_action_popup_text_pressed" package="miui">#ffff8cee</color>
              <color name="text_edit_action_popup_more_normal_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_highlight_pressed_light" >#ffff8cee</color>
              <color name="miuix_appcompat_list_text_color_checked_light" >#ffff8cee</color>
              <color name="miuix_appcompat_number_picker_highlight_text_color" >#ffff8cee</color>
              <color name="miuix_appcompat_dropdown_popup_list_text_color_checked_light" >#ffff8cee</color>
              <color name="miuix_appcompat_text_edit_action_popup_text_pressed" >#ffff8cee</color>
              <color name="miuix_appcompat_text_edit_action_popup_more_normal_light" >#ffff8cee</color>
              <color name="miuix_appcompat_number_picker_highlight_color" >#ffff8cee</color>
              <color name="miuix_appcompat_number_picker_label_color" >#ffff8cee</color>
              <color name="miuix_compat_list_text_color_checked_light" >#ffff8cee</color>
              <color name="record_audio_dialog_bg" >#ffffffff</color>
              <color name="dialog_bg_color_light" package="miui">#ffffffff</color>
              <color name="miuix_appcompat_dialog_bg_color_light" >#ffffffff</color>
              <color name="button_bg_primary_color_disabled_light" package="miui">#0d000000</color>
              <color name="miuix_appcompat_button_bg_primary_color_disabled_light" >#0d000000</color>
              <color name="button_text_color_guide_disabled_light" package="miui">#4d000000</color>
              <color name="miuix_appcompat_button_text_color_guide_disabled_light" >#4d000000</color>
              <color name="button_bg_primary_color_normal_light" package="miui">#ffff8cee</color>
              <color name="button_bg_primary_color_pressed_light" package="miui">#ffff8cee</color>
              <color name="button_bg_color_warn_normal_light" package="miui">#ffff8cee</color>
              <color name="button_bg_color_warn_pressed_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_button_bg_color_warn_normal_light" >#ffff8cee</color>
              <color name="miuix_appcompat_button_bg_color_warn_pressed_light" >#ffff8cee</color>
              <color name="miuix_appcompat_button_bg_primary_color_normal_light" >#ffff8cee</color>
              <color name="miuix_appcompat_button_bg_primary_color_pressed_light" >#ffff8cee</color>
              <color name="button_text_color_guide_normal_light" package="miui">#ffffffff</color>
              <color name="miuix_appcompat_button_text_color_guide_normal_light" >#ffffffff</color>
              <color name="list_item_bg_color_pressed_light" package="miui">#0d000000</color>
              <color name="miuix_folme_color_touch_tint" >#0d000000</color>
              <color name="folme_color_touch_tint" package="miui">#0d000000</color>
              <color name="dropdown_popup_list_item_bg_pressed_light" package="miui">#0d000000</color>
              <color name="text_select_item_bg_color_pressed_light" package="miui">#0d000000</color>
              <color name="miuix_appcompat_list_item_bg_color_pressed_light" >#0d000000</color>
              <color name="miuix_appcompat_folme_color_touch_tint" >#0d000000</color>
              <color name="miuix_appcompat_dropdown_popup_list_item_bg_pressed_light" >#0d000000</color>
              <color name="miuix_appcompat_text_select_item_bg_color_pressed_light" >#0d000000</color>
              <color name="list_item_bg_color_checked_light" package="miui">#0d4eaa8a</color>
              <color name="dropdown_popup_list_item_bg_checked_light" package="miui">#0d4eaa8a</color>
              <color name="miuix_appcompat_list_item_bg_color_checked_light" >#0d4eaa8a</color>
              <color name="miuix_appcompat_dropdown_popup_list_item_bg_checked_light" >#0d4eaa8a</color>
              <color name="miuix_appcompat_list_item_bg_dialog_color_checked_light" >#0d4eaa8a</color>
              <color name="miuix_appcompat_spinner_item_checked_bg_color_light" >#0d4eaa8a</color>
              <color name="edit_text_border_color" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_edit_text_border_color" >#ffff8cee</color>
              <color name="edit_text_dialog_bg_solid_light" package="miui">#fff0f0f0</color>
              <color name="edit_text_bg_color_light" package="miui">#fff0f0f0</color>
              <color name="miuix_appcompat_edit_text_dialog_bg_solid_light" >#fff0f0f0</color>
              <color name="miuix_appcompat_edit_text_bg_color_light" >#fff0f0f0</color>
              <color name="word_photo_color" package="miui">#f4ffffff</color>
              <color name="word_photo_color" >#f4ffffff</color>
              <color name="fab_bg_color" >#ffff8cee</color>
              <color name="new_border_color" >#1a000000</color>
              <color name="recent_recipient_text_bg_color" >#0d000000</color>
              <color name="message_bubble_in_bg_n" >#ffffffff</color>
              <color name="message_bubble_in_bg_p" >#fffafafa</color>
              <color name="message_bubble_out_bg_n" >#ffff8cee</color>
              <color name="message_bubble_out_bg_p" >#ffff8cee</color>
              <color name="mi_message_bubble_out_bg_n" >#ff2d74ff</color>
              <color name="mi_message_bubble_out_bg_p" >#ff2d74ff</color>
              <color name="text_color_message_in" >#e6000000</color>
              <color name="text_color_message_in_pressed" >#e6000000</color>
              <color name="audio_item_in_text_color" >#e6000000</color>
              <color name="text_color_message_in_highlight" >#ffff8cee</color>
              <color name="text_color_message_in_highlight_pressed" >#ffff8cee</color>
              <color name="understand_button_color" >#0d4eaa8a</color>
              <color name="understand_button_text" >#ffff8cee</color>
              <color name="text_color_message_out" >#e6ffffff</color>
              <color name="text_color_message_out_pressed" >#e6ffffff</color>
              <color name="text_color_message_out_mx" >#e6ffffff</color>
              <color name="text_color_message_out_mx_pressed" >#e6ffffff</color>
              <color name="audio_item_out_text_color" >#e6ffffff</color>
              <color name="text_color_message_out_highlight" >#ffffffee</color>
              <color name="text_color_message_out_highlight_pressed" >#ffffffee</color>
              <color name="text_color_message_alert_highlight" >#ffffffee</color>
              <color name="text_color_message_alert_highlight_pressed" >#ffffffee</color>
              <color name="text_color_message_alert" >#ffffffee</color>
              <color name="text_color_message_alert_pressed" >#ffffffee</color>
              <color name="text_color_message_out_sendtitle" >#ffffffee</color>
              <color name="text_color_message_out_sendtitle_pressed" >#ffffffee</color>
              <color name="sim_button_container_color" >#ffffffff</color>
              <color name="bottom_sub_menu_bg_color" >#ffffffff</color>
              <color name="button_send_slot_bg_p" >#1a4eaa8a</color>
              <color name="hint_edit_text_color_light" >#66000000</color>
              <color name="hint_edit_text_color_light" package="miui">#66000000</color>
              <color name="miuix_appcompat_hint_edit_text_color_light" >#66000000</color>
              <color name="edit_text_color_light" package="miui">#e6000000</color>
              <color name="miuix_appcompat_edit_text_color_light" >#e6000000</color>
              <color name="list_secondary_text_color_normal_light_message" >#99000000</color>
              <color name="list_secondary_text_color_pressed_light_message" >#99000000</color>
              <color name="list_secondary_text_color_disable_light_message" >#99000000</color>
              <color name="card_bottom_menu_button_color" >#0d000000</color>
              <color name="slide_controler_bg" >#0d000000</color>
              <color name="record_audio_btn_editor" >#0d000000</color>
              <color name="record_audio_btn_editor_p" >#0d000000</color>
              <color name="text_color_attachment_edit_phrase" >#ffff8cee</color>
              <color name="text_color_attachment_type_name" >#e6000000</color>
              <color name="text_color_attachment_type" >#e6000000</color>
              <color name="screen_view_seek_point_highlight" >#e6000000</color>
              <color name="text_color_attachment_type_name_disabled" >#4d000000</color>
              <color name="screen_view_seek_point_normal" >#4d000000</color>
              <color name="bottom_menu_text_color" >#e6000000</color>
              <color name="text_color_bottom_menu_button" >#ffff8cee</color>
              <color name="border_color" >#26000000</color>
              <color name="contact_card_bg_color_n" >#0d000000</color>
              <color name="contact_card_bg_color_p" >#0d000000</color>
              <color name="card_background_covered_bg_n" >#fff5f5f5</color>
              <color name="card_background_covered_bg_p" >#fff5f5f5</color>
              <color name="ic_insert_contact_color" >#ffff8cee</color>
              <color name="verification_activity_background" >#ffffffff</color>
              <color name="new_card_body_bg" >#0a000000</color>
              <color name="bank_subtitle_color" >#ff8c93b0</color>
              <color name="train_card_action_text_primary" >#ffff8cee</color>
              <color name="link_text_color_normal" >#ffff8cee</color>
              <color name="link_text_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_link_text_light" >#ffff8cee</color>
              <color name="card_body_bg" >#ffffffff</color>
              <color name="verfication_card_bottom_button_bg" >#ffffffff</color>
              <color name="card_bottom_button_bg" >#ffffffff</color>
              <color name="contact_card_divider_color" >#0f000000</color>
              <color name="verification_code_raw_content_divider_color" >#0f000000</color>
              <color name="card_divider_bg" >#0f000000</color>
              <color name="card_border" >#26000000</color>
              <color name="tab_list_card_border" >#26000000</color>
              <color name="understand_float_text_color" >#ffff8cee</color>
              <color name="sliding_button_bar_off_light" package="miui">#26000000</color>
              <color name="miuix_appcompat_sliding_button_bar_off_light" >#26000000</color>
              <color name="sliding_button_bar_on_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_sliding_button_bar_on_light" >#ffff8cee</color>
              <color name="sliding_btn_slider_off_normal_color_light" package="miui">#ffffffff</color>
              <color name="sliding_btn_slider_off_pressed_color_light" package="miui">#ffffffff</color>
              <color name="sliding_btn_slider_on_normal_color_light" package="miui">#ffffffff</color>
              <color name="sliding_btn_slider_on_pressed_color_light" package="miui">#ffffffff</color>
              <color name="miuix_appcompat_sliding_btn_slider_off_normal_color_light" >#ffffffff</color>
              <color name="miuix_appcompat_sliding_btn_slider_off_pressed_color_light" >#ffffffff</color>
              <color name="miuix_appcompat_sliding_btn_slider_on_normal_color_light" >#ffffffff</color>
              <color name="miuix_appcompat_sliding_btn_slider_on_pressed_color_light" >#ffffffff</color>
              <color name="svg_icon_color_normal" >#e6000000</color>
              <color name="svg_icon_color_normal_light" package="miui">#e6000000</color>
              <color name="action_mode_button_text_color_normal_light" package="miui">#e6000000</color>
              <color name="action_button_text_color_normal_light" package="miui">#e6000000</color>
              <color name="miuix_appcompat_svg_icon_color_normal_light" >#e6000000</color>
              <color name="miuix_appcompat_action_mode_button_text_color_normal_light" >#e6000000</color>
              <color name="miuix_appcompat_action_button_text_color_normal_light" >#e6000000</color>
              <color name="svg_icon_color_pressed" >#99000000</color>
              <color name="svg_icon_color_pressed_light" package="miui">#99000000</color>
              <color name="svg_icon_color_blue_pressed_light" package="miui">#99000000</color>
              <color name="svg_icon_color_red_pressed_light" package="miui">#99000000</color>
              <color name="action_mode_button_text_color_pressed_light" package="miui">#99000000</color>
              <color name="action_button_text_color_pressed_light" package="miui">#99000000</color>
              <color name="miuix_appcompat_svg_icon_color_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_svg_icon_color_blue_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_svg_icon_color_red_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_action_mode_button_text_color_pressed_light" >#99000000</color>
              <color name="miuix_appcompat_action_button_text_color_pressed_light" >#99000000</color>
              <color name="svg_icon_color_disable" >#4d000000</color>
              <color name="svg_icon_color_disable_light" package="miui">#4d000000</color>
              <color name="svg_icon_color_blue_disable_light" package="miui">#4d000000</color>
              <color name="svg_icon_color_red_disable_light" package="miui">#4d000000</color>
              <color name="action_mode_button_text_color_disable_light" package="miui">#4d000000</color>
              <color name="action_button_text_color_disable_light" package="miui">#4d000000</color>
              <color name="miuix_appcompat_svg_icon_color_disable_light" >#4d000000</color>
              <color name="miuix_appcompat_svg_icon_color_blue_disable_light" >#4d000000</color>
              <color name="miuix_appcompat_svg_icon_color_red_disable_light" >#4d000000</color>
              <color name="miuix_appcompat_action_mode_button_text_color_disable_light" >#4d000000</color>
              <color name="miuix_appcompat_action_button_text_color_disable_light" >#4d000000</color>
              <color name="svg_icon_color_blue_normal_light" package="miui">#ffff8cee</color>
              <color name="svg_icon_color_blue_selected_light" package="miui">#ffff8cee</color>
              <color name="action_button_text_color_selected_light" package="miui">#ffff8cee</color>
              <color name="action_mode_button_text_color_selected_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_svg_icon_color_blue_normal_light" >#ffff8cee</color>
              <color name="miuix_appcompat_svg_icon_color_blue_selected_light" >#ffff8cee</color>
              <color name="miuix_appcompat_action_button_text_color_selected_light" >#ffff8cee</color>
              <color name="miuix_appcompat_action_mode_button_text_color_selected_light" >#ffff8cee</color>
              <color name="svg_icon_color_red_normal_light" package="miui">#fff22424</color>
              <color name="miuix_appcompat_svg_icon_color_red_normal_light" >#fff22424</color>
              <color name="checkbox_btn_stroke_color_light" package="miui">#ff000000</color>
              <color name="miuix_appcompat_checkbox_btn_stroke_color_light" >#ff000000</color>
              <color name="checkbox_btn_disable_background_color_light" package="miui">#ff000000</color>
              <color name="miuix_appcompat_checkbox_btn_disable_background_color_light" >#ff000000</color>
              <color name="checkbox_btn_on_background_color_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_checkbox_btn_on_background_color_light" >#ffff8cee</color>
              <color name="checkbox_btn_on_foreground_color_light" package="miui">#ffffffff</color>
              <color name="miuix_appcompat_checkbox_btn_on_foreground_color_light" >#ffffffff</color>
              <color name="button_bg_dialog_color_normal_light" package="miui">#1a000000</color>
              <color name="miuix_appcompat_button_bg_color_normal_light" >#1a000000</color>
              <color name="text_select_item_bg_color_normal_light" package="miui">#00ffffff</color>
              <color name="miuix_appcompat_text_select_item_bg_color_normal_light" >#00ffffff</color>
              <color name="miuix_preference_first_last_divider_line_light" >#1affffff</color>
              <color name="audio_progress_window_background" >#99000000</color>
              <color name="view_press_mask" >#1affffff</color>
              <color name="mask_view_pressed" >#0dffffff</color>
              <color name="dropdown_popup_list_item_bg_normal_light" package="miui">#00ffffff</color>
              <color name="divider_color_light" package="miui">#0dffffff</color>
              <color name="miuix_appcompat_dropdown_popup_list_item_bg_normal_light" >#00ffffff</color>
              <color name="miuix_appcompat_divider_color_light" >#0dffffff</color>
              <color name="miuix_appcompat_spinner_item_normal_bg_color_light" >#00ffffff</color>
              <color name="miuix_appcompat_white" >#00ffffff</color>
              <color name="miuix_appcompat_number_picker_highlight_region_bg_color" >#001affff</color>
            </MIUI_Theme_Values>
      ''',
    "com.android.systemui": '''
          <?xml version="1.0" encoding="utf-8"?>
            <MIUI_Theme_Values template="LightTemplate">
              <color name="notification_actions_button_color" >#ffff8cee</color>
              <color name="notification_overflow_number_color" >#ffff8cee</color>
              <color name="notification_action_text_color" >#ffff8cee</color>
              <color name="notification_default_color_light" package="android">#ffff8cee</color>
              <color name="notification_setting_button_color" >#ffff8cee</color>
              <color name="notification_group_collapsed_button_color" >#ffff8cee</color>
              <color name="recent_tick_anim_color" >#ffff8cee</color>
              <color name="qs_control_tile_icon_enable_color" >#ffff8cee</color>
              <color name="qs_control_big_tile_green_bg" >#ffff8cee</color>
              <color name="qs_control_big_tile_blue_bg" >#ffff8cee</color>
              <color name="cc_qs_tile_icon_bg_color_active" >#ffff8cee</color>
              <color name="qs_detail_item_selected_color" >#ffff8cee</color>
              <color name="qs_tile_icon_bg_enabled_color" >#ffff8cee</color>
              <color name="sliding_button_bar_on_light" package="miui">#ffff8cee</color>
              <color name="miuix_appcompat_sliding_button_bar_on_light" >#ffff8cee</color>
              <color name="status_bar_network_flow_exceed_color" >#ffff8cee</color>
              <color name="cc_qs_tile_icon_bg_color_active_battery_related" >#ffff8cee</color>
              <color name="qs_control_brightness_progress_color" >#ffff8cee</color>
              <color name="qs_control_tiles_expand_indicator_color" >#ffff8cee</color>
              <color name="qs_control_big_tile_white_bg" >#ffff8cee</color>
              <color name="qs_tile_icon_bg_disabled_color" >#ffffffff</color>
            </MIUI_Theme_Values>'''
  };
}
