const List<String> kBuffyCategories = [
  'Abstract',
  'Amoled',
  'Animals',
  'Anime',
  'Banners',
  'Buffy Setups',
  'Cartoon',
  'Celebrations',
  'Creative',
  'Cyberpunk',
  'Drive Mode',
  'Festivals',
  'First Love',
  'Foody',
  'Free',
  'Funny Art',
  'Gaming',
  'Gradient',
  'Horror',
  'Hypnotiq',
  'Minimal',
  'Minimal Illustrations',
  'Movies and Series',
  'Nature',
  'Night Life',
  'Pastel',
  'PW Testing',
  'Sci-fi',
  'Spiritual',
  'Sports',
  'Stock',
  'Stories of India',
  'Superheroes',
];
