import 'dart:io';
import 'dart:ui' show lerpDouble;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:video_player_media_kit/video_player_media_kit.dart';

// ── Shared theme ──────────────────────────────────────────────────────────────
import 'core/theme/app_colors.dart';
import 'core/theme/app_theme.dart';
import 'core/theme/app_radius.dart';
import 'core/theme/theme_extensions.dart';
import 'core/theme/theme_provider.dart';

// ── Theme Editor imports ──────────────────────────────────────────────────────
import 'theme_editor/core/services/window_service.dart';
import 'theme_editor/presentation/features/splash/user_profile_screen.dart';
import 'theme_editor/presentation/providers/service_providers.dart';

// ── Image Utility imports ─────────────────────────────────────────────────────
import 'image_utility/core/utils/windows.dart';
import 'image_utility/core/router/app_router.dart';

// ── Theme Deployment imports ──────────────────────────────────────────────────
import 'theme_deployment/presentation/pages/deployment_page.dart';

// ── WallRio CMS imports ───────────────────────────────────────────────────────
import 'package:hive_flutter/hive_flutter.dart';
import 'wall_rio/application/providers/router_provider.dart';
import 'wall_rio/domain/models/cms_models.dart';


// ── BuffyWalls CMS imports ────────────────────────────────────────────────────
import 'buffy_walls/presentation/screens/buffy_dashboard_screen.dart';


// =============================================================================

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Hive for WallRio CMS — adapters are generated by build_runner
  await Hive.initFlutter();
  Hive.registerAdapter(SavedFilePathImplAdapter());
  Hive.registerAdapter(LocalVersionImplAdapter());

  // Desktop window
  if (Platform.isWindows || Platform.isMacOS || Platform.isLinux) {
    await WindowService.init();
    await startUpWindowsUtils();
  }

  // Android permissions
  if (Platform.isAndroid) {
    await [
      Permission.storage,
      Permission.manageExternalStorage,
    ].request();
  }

  // Video player
  VideoPlayerMediaKit.ensureInitialized(
    android: true,
    iOS: true,
    macOS: true,
    windows: true,
  );

  // Global error widget
  ErrorWidget.builder = (details) => Container(
        decoration: const BoxDecoration(
          color: AppColors.darkSurface0,
          borderRadius: AppRadius.radiusMd,
        ),
        alignment: Alignment.center,
        padding: const EdgeInsets.all(16),
        child: Text(
          details.exceptionAsString(),
          textAlign: TextAlign.center,
          style: const TextStyle(color: AppColors.errorDark, fontSize: 11),
        ),
      );

  final prefs = await SharedPreferences.getInstance();

  runApp(
    ProviderScope(
      overrides: [sharedPrefsProvider.overrideWithValue(prefs)],
      child: const RootApp(),
    ),
  );
}

// =============================================================================
// Root app — shows the launcher, hosts both sub-apps via Navigator
// =============================================================================

class RootApp extends ConsumerWidget {
  const RootApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeModeProvider);
    return MaterialApp(
      title: 'Team Shadow Tools',
      debugShowCheckedModeBanner: false,
      themeMode: themeMode,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      home: const AppLauncherScreen(),
    );
  }
}

// =============================================================================
// Launcher — add new apps here forever, no other file needs to change
// =============================================================================

class _AppEntry {
  const _AppEntry({
    required this.title,
    required this.subtitle,
    required this.icon,
    required this.color,
    required this.builder,
    this.bgImageDark,
    this.bgImageLight,
  });

  final String title;
  final String subtitle;
  final IconData icon;
  final Color color;
  final String? bgImageDark;
  final String? bgImageLight;

  /// Returns the root widget of the sub-app.
  /// Each sub-app is fully self-contained — its own MaterialApp / router.
  final Widget Function() builder;
}

// ── Register apps here ────────────────────────────────────────────────────────

final List<_AppEntry> _apps = [
  _AppEntry(
    title: 'Theme Editor',
    subtitle: 'Lockscreen · Icons · Module · MTZ',
    icon: Icons.layers_rounded,
    color: AppColors.purplePrimary,
    bgImageDark: 'assets/images/theme_editor.png',
    bgImageLight: 'assets/images/theme_editor_light.png',
    builder: () => const _ThemeEditorApp(),
  ),
  _AppEntry(
    title: 'Image Utility',
    subtitle: 'Resize · Crop · Convert · Export',
    icon: Icons.image_rounded,
    color: AppColors.purpleHover,
    bgImageDark: 'assets/images/image_utility.png',
    bgImageLight: 'assets/images/image_utility_light.png',
    builder: () => const _ImageUtilityApp(),
  ),
  _AppEntry(
    title: 'Themes Deployment',
    subtitle: 'Upload · Designer Portal · Automation',
    icon: Icons.rocket_launch,
    color: AppColors.purpleSelection,
    bgImageDark: 'assets/images/deployment.png',
    bgImageLight: 'assets/images/deployment_light.png',
    builder: () => const _ThemeDeploymentApp(),
  ),
  _AppEntry(
    title: 'WallRio CMS',
    subtitle: 'Wallpapers · Git · Analytics · Push',
    icon: Icons.wallpaper_rounded,
    color: AppColors.purplePressed,
    bgImageDark: 'assets/images/wallrio.png',
    bgImageLight: 'assets/images/wallrio_light.png',
    builder: () => const _WallRioCMSApp(),
  ),
  _AppEntry(
    title: 'BuffyWalls CMS',
    subtitle: 'Wallpapers · Categories · GitLab Push',
    icon: Icons.dashboard_customize_rounded,
    color: AppColors.purpleHover,
    bgImageDark: 'assets/images/buffywalls.png',
    bgImageLight: 'assets/images/buffywalls_light.png',
    builder: () => const _BuffyWallsCMSApp(),
  ),
];

// ─────────────────────────────────────────────────────────────────────────────

class AppLauncherScreen extends ConsumerWidget {
  const AppLauncherScreen({super.key});

  void _launch(BuildContext context, _AppEntry app) {
    Navigator.of(context).push(
      PageRouteBuilder(
        pageBuilder: (_, animation, __) => app.builder(),
        transitionsBuilder: (_, animation, __, child) => FadeTransition(
          opacity: animation,
          child: child,
        ),
        transitionDuration: const Duration(milliseconds: 300),
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final colors = context.appColors;
    final themeMode = ref.watch(themeModeProvider);
    final notifier = ref.read(themeModeProvider.notifier);

    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(40),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header row
              Row(
                children: [
                  const SizedBox(width: 4),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 20),
                        Text(
                          'Team Shadow Tools',
                          style: Theme.of(context)
                              .textTheme
                              .displaySmall
                              ?.copyWith(fontWeight: FontWeight.bold),
                        ),
                        const SizedBox(height: 8),
                        Text(
                          'Select a tool to get started',
                          style: Theme.of(context)
                              .textTheme
                              .bodyLarge
                              ?.copyWith(color: colors.textSecondary),
                        ),
                      ],
                    ),
                  ),
                  // Theme toggle
                  Tooltip(
                    message: themeMode == ThemeMode.dark
                        ? 'Switch to Light Mode'
                        : 'Switch to Dark Mode',
                    child: IconButton(
                      onPressed: notifier.toggle,
                      icon: Icon(
                        themeMode == ThemeMode.dark
                            ? Icons.light_mode_rounded
                            : Icons.dark_mode_rounded,
                        color: colors.primary,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 48),
              // App grid
              Expanded(
                child: GridView.builder(
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 3,
                    crossAxisSpacing: 20,
                    mainAxisSpacing: 20,
                    childAspectRatio: 1.8,
                  ),
                  itemCount: _apps.length,
                  itemBuilder: (context, i) => TweenAnimationBuilder<double>(
                    tween: Tween(begin: 0.0, end: 1.0),
                    duration: Duration(milliseconds: 350 + i * 70),
                    curve: Curves.easeOutCubic,
                    builder: (context, v, child) => Opacity(
                      opacity: v,
                      child: Transform.translate(
                        offset: Offset(0, 24 * (1 - v)),
                        child: child,
                      ),
                    ),
                    child: _AppCard(
                      app: _apps[i],
                      onTap: () => _launch(context, _apps[i]),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────

class _AppCard extends StatefulWidget {
  const _AppCard({required this.app, required this.onTap});
  final _AppEntry app;
  final VoidCallback onTap;

  @override
  State<_AppCard> createState() => _AppCardState();
}

class _AppCardState extends State<_AppCard> with SingleTickerProviderStateMixin {
  late final AnimationController _hoverCtrl;
  late final Animation<double> _enterAnim;

  double _mouseX = 0.5;
  double _mouseY = 0.5;

  @override
  void initState() {
    super.initState();
    _hoverCtrl = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 280),
    );
    _enterAnim = CurvedAnimation(parent: _hoverCtrl, curve: Curves.easeOut);
  }

  @override
  void dispose() {
    _hoverCtrl.dispose();
    super.dispose();
  }

  void _onHover(PointerEvent event) {
    final box = context.findRenderObject() as RenderBox?;
    if (box == null) return;
    final local = box.globalToLocal(event.position);
    setState(() {
      _mouseX = (local.dx / box.size.width).clamp(0.0, 1.0);
      _mouseY = (local.dy / box.size.height).clamp(0.0, 1.0);
    });
  }

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      cursor: SystemMouseCursors.click,
      onEnter: (_) => _hoverCtrl.forward(),
      onExit: (_) => _hoverCtrl.reverse(),
      onHover: _onHover,
      child: GestureDetector(
        onTap: widget.onTap,
        child: AnimatedBuilder(
          animation: _hoverCtrl,
          builder: (context, _) {
            final t = _enterAnim.value;
            final color = widget.app.color;

            // 3D tilt toward cursor
            final tiltX = (_mouseY - 0.5) * -0.10 * t;
            final tiltY = (_mouseX - 0.5) * 0.10 * t;
            final tiltMatrix = Matrix4.identity()
              ..setEntry(3, 2, 0.001)
              ..rotateX(tiltX)
              ..rotateY(tiltY);

            // Spotlight alignment follows cursor
            final spotX = (_mouseX * 2) - 1;
            final spotY = (_mouseY * 2) - 1;

            return Transform(
              transform: tiltMatrix,
              alignment: Alignment.center,
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: AppRadius.radiusXl,
                  boxShadow: [
                    BoxShadow(
                      color: color.withAlpha((90 * t).toInt()),
                      blurRadius: lerpDouble(6, 40, t)!,
                      offset: Offset(
                        (_mouseX - 0.5) * 10 * t,
                        lerpDouble(2, 20, t)! + (_mouseY - 0.5) * 6 * t,
                      ),
                    ),
                  ],
                ),
                child: ClipRRect(
                  borderRadius: AppRadius.radiusXl,
                  child: Stack(
                    fit: StackFit.expand,
                    children: [
                      // Background image
                      if (widget.app.bgImageDark != null || widget.app.bgImageLight != null)
                        Image.asset(
                          (Theme.of(context).brightness == Brightness.dark
                                  ? widget.app.bgImageDark
                                  : widget.app.bgImageLight) ??
                              widget.app.bgImageDark ??
                              widget.app.bgImageLight!,
                          fit: BoxFit.cover,
                        ),

                      // Dark overlay — lifts on hover
                      Container(
                        color: (Theme.of(context).brightness == Brightness.dark 
                                ? Colors.black 
                                : Colors.white).withAlpha(
                          lerpDouble(115, 50, t)!.toInt(),
                        ),
                      ),

                      // White spotlight following cursor
                      Positioned.fill(
                        child: IgnorePointer(
                          child: Container(
                            decoration: BoxDecoration(
                              gradient: RadialGradient(
                                center: Alignment(spotX, spotY),
                                radius: 0.75,
                                colors: [
                                  Colors.white.withAlpha((55 * t).toInt()),
                                  Colors.transparent,
                                ],
                              ),
                            ),
                          ),
                        ),
                      ),

                      // Accent color bloom at cursor
                      Positioned.fill(
                        child: IgnorePointer(
                          child: Container(
                            decoration: BoxDecoration(
                              gradient: RadialGradient(
                                center: Alignment(spotX, spotY),
                                radius: 0.5,
                                colors: [
                                  color.withAlpha((50 * t).toInt()),
                                  Colors.transparent,
                                ],
                              ),
                            ),
                          ),
                        ),
                      ),

                      // Border glow
                      Container(
                        decoration: BoxDecoration(
                          borderRadius: AppRadius.radiusXl,
                          border: Border.all(
                            color: Color.lerp(
                              Colors.white.withAlpha(30),
                              color.withAlpha(210),
                              t,
                            )!,
                            width: lerpDouble(1.0, 1.5, t)!,
                          ),
                        ),
                      ),

                      // Text — top right
                      Positioned(
                        top: 18,
                        right: 18,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.end,
                          children: [
                            Text(
                              widget.app.title,
                              style: Theme.of(context)
                                  .textTheme
                                  .titleMedium
                                  ?.copyWith(
                                    fontWeight: FontWeight.w700,
                                    color: Theme.of(context).brightness == Brightness.dark 
                                        ? Colors.white 
                                        : Colors.black87,
                                    shadows: Theme.of(context).brightness == Brightness.dark 
                                        ? [
                                            Shadow(
                                              color: Colors.black.withAlpha(140),
                                              blurRadius: 8,
                                            ),
                                          ]
                                        : null,
                                  ),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              widget.app.subtitle,
                              style: Theme.of(context)
                                  .textTheme
                                  .bodySmall
                                  ?.copyWith(
                                    color: Theme.of(context).brightness == Brightness.dark 
                                        ? Colors.white70 
                                        : Colors.black54,
                                  ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

// =============================================================================
// Sub-app wrappers — each is a full MaterialApp / router in its own scope
// =============================================================================

// ── Theme Editor ──────────────────────────────────────────────────────────────

class _ThemeEditorApp extends ConsumerWidget {
  const _ThemeEditorApp();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeModeProvider);
    return MaterialApp(
      title: 'MIUI Theme Editor',
      debugShowCheckedModeBanner: false,
      themeMode: themeMode,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      home: const UserProfileScreen(),
    );
  }
}

// ── Image Utility ─────────────────────────────────────────────────────────────

class _ImageUtilityApp extends ConsumerWidget {
  const _ImageUtilityApp();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    final themeMode = ref.watch(themeModeProvider);
    return MaterialApp.router(
      title: 'Image Utility',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: themeMode,
      routerConfig: router,
    );
  }
}

// ── Themes Deployment ─────────────────────────────────────────────────────────

class _ThemeDeploymentApp extends ConsumerWidget {
  const _ThemeDeploymentApp();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeModeProvider);
    return MaterialApp(
      title: 'Themes Deployment',
      debugShowCheckedModeBanner: false,
      themeMode: themeMode,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      home: const DeploymentPage(),
    );
  }
}

// ── WallRio CMS ───────────────────────────────────────────────────────────────

class _WallRioCMSApp extends ConsumerWidget {
  const _WallRioCMSApp();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(wallRioRouterProvider);
    final themeMode = ref.watch(themeModeProvider);
    return MaterialApp.router(
      title: 'WallRio CMS',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: themeMode,
      routerConfig: router,
    );
  }
}

// ── BuffyWalls CMS ────────────────────────────────────────────────────────────

class _BuffyWallsCMSApp extends ConsumerWidget {
  const _BuffyWallsCMSApp();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeModeProvider);
    return MaterialApp(
      title: 'BuffyWalls CMS',
      debugShowCheckedModeBanner: false,
      themeMode: themeMode,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      home: const BuffyDashboardScreen(),
    );
  }
}

