enum IconShape {
  squircle,
  hexagon,
  octagon,
  pentagon,
  shield,
  ticket,
  pebble,
  blob,
  star,
  diamond,
  cloud,
  triangle,
  heart,
  capsule,
  leaf,
  ring,
  trapezoid;

  String get label => switch (this) {
        squircle => 'Squircle',
        hexagon => 'Hexagon',
        octagon => 'Octagon',
        pentagon => 'Pentagon',
        shield => 'Shield',
        ticket => 'Ticket',
        pebble => 'Pebble',
        blob => 'Blob',
        star => 'Star',
        diamond => 'Diamond',
        cloud => 'Cloud',
        triangle => 'Triangle',
        heart => 'Heart',
        capsule => 'Capsule',
        leaf => 'Leaf',
        ring => 'Ring',
        trapezoid => 'Trapeze',
      };
}
