name: Miui Theme Editor Build Generation For Mac OS

on:
  push:
    tags: ["build-macos-vs", "build-macos-vp"]

permissions:
  contents: write

jobs:
  build-and-release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable mac os support
        run: flutter config --enable-macos-desktop
      - name: Flutter Build Release for Mac OS
        run: flutter build macos --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: Miui-Editor-${{github.ref_name}}-macos.zip
          directory: build/macos/Build/Products/Release
      - name: Mac OS Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/macos/Build/Products/Release/Miui-Editor-${{github.ref_name}}-macos.zip
